Movies Domain Layer
Pabloyquemas/Films-2022 pull request #1
Opened 2022-11-09 14:28 UTC by Pabloyquemas

## Description de la tarea

Implementación de la capa de dominio

## ¿Cómo se ha implementado?

He implementado un modelo de datos(data class), una interfaz llamada Repositories con el repositorio de Movies y una clase que la utilizo como caso de uso

## Keywords

data class, interface, modelo de datos, use case

## Screenshots or Video

## Objetivos

## Disclaimer

## Criterios de Evaluación

2022-11-09 21:52 UTC, josem-perram requested changes
Please, revisa el comentario, corrígelo y actualiza la PR.

2022-11-09 21:52 UTC, josem-perram commented on app/src/main/java/com/example/films_2022/domain/Repositories.kt
> +    fun GetMovies(): List <Movies>
mmm las funciones con mayúsculas?? Por favor, revisa el proyectos anteriores el naming de las funciones ;)

2022-11-14 18:53 UTC, Pabloyquemas reviewed
arreglado mayus en las func

2022-11-17 07:43 UTC, josem-perram requested changes
Por favor, revisa el comentario.

2022-11-17 07:43 UTC, josem-perram commented on app/src/main/java/com/example/films_2022/domain/GetMoviesUseCase.kt
> +        return emptyList()
emptyList??

2022-11-18 14:33 UTC, josem-perram approved these changes
Genial! 🚀

2022-11-18 18:00 UTC, merged